/**
 * useGammaOrders — Gamma Spec order communication via NIP-17 encrypted DMs
 *
 * Order flow uses encrypted kind 16 messages with typed sub-protocols:
 *
 *   type "1" — Order Creation (buyer → merchant)
 *   type "2" — Payment Request (merchant → buyer)
 *   type "3" — Order Status Update (merchant → buyer, or buyer cancel)
 *   type "4" — Shipping Update (merchant → buyer)
 *   kind 17   — Payment Receipt (buyer → merchant)
 *   kind 14   — General Communication
 *
 * See: https://github.com/GammaMarkets/market-spec/blob/main/spec.md#4-order-communication-flow-and-payment-processing
 *
 * NIP-17 uses kind 1059 (gift wrap) for the outer envelope, but for
 * simplicity this implementation uses kind 4 (legacy NIP-04) as the
 * encryption layer since most signers support it, with a migration path
 * to full NIP-17 gift wrap when signers support it.
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNostr } from '@nostrify/react';
import { useCurrentUser } from './useCurrentUser';
import { useToast } from './useToast';
import { getAdminPubkeyHex } from '@/lib/adminUtils';
import { storeOrder, getStoredOrders } from './useOrders';
import type { Order } from './useOrders';

// ─── Types ─────────────────────────────────────────────────────────────────────

export type GammaOrderStatus =
  | 'pending'
  | 'confirmed'
  | 'processing'
  | 'completed'
  | 'cancelled';

export type GammaShippingStatus =
  | 'processing'
  | 'shipped'
  | 'delivered'
  | 'exception';

export interface GammaOrderItem {
  /** "30402:<pubkey>:<d-tag>" */
  productRef: string;
  quantity: number;
  /** Human-readable fallback */
  productName?: string;
}

export interface GammaOrder {
  /** Unique order identifier (generated by buyer) */
  orderId: string;
  /** Total amount in satoshis */
  amountSats: number;
  /** Items ordered */
  items: GammaOrderItem[];
  /** Optional: reference to shipping option "30406:<pubkey>:<d>" */
  shippingRef?: string;
  /** Shipping address */
  address?: string;
  email?: string;
  phone?: string;
  notes?: string;
}

export interface GammaPaymentRequest {
  orderId: string;
  amountSats: number;
  lightning?: string;
  bitcoin?: string;
  ecash?: string;
  expiration?: number;
  notes?: string;
}

export interface GammaStatusUpdate {
  orderId: string;
  status: GammaOrderStatus;
  message?: string;
}

export interface GammaShippingUpdate {
  orderId: string;
  status: GammaShippingStatus;
  trackingNumber?: string;
  carrier?: string;
  eta?: number;
  message?: string;
}

// ─── Message builders ──────────────────────────────────────────────────────────

/** Build kind 16 order creation message content */
function buildOrderCreationContent(order: GammaOrder, merchantPubkey: string): { content: object; tags: string[][] } {
  const tags: string[][] = [
    ['p', merchantPubkey],
    ['subject', `Order ${order.orderId}`],
    ['type', '1'],
    ['order', order.orderId],
    ['amount', order.amountSats.toString()],
    ...order.items.map(item => ['item', item.productRef, item.quantity.toString()]),
  ];

  if (order.shippingRef) tags.push(['shipping', order.shippingRef]);
  if (order.address) tags.push(['address', order.address]);
  if (order.email) tags.push(['email', order.email]);
  if (order.phone) tags.push(['phone', order.phone]);

  return {
    content: { type: 1, order: order.orderId, items: order.items, amount: order.amountSats },
    tags,
  };
}

/** Build kind 16 payment request message (merchant → buyer) */
function buildPaymentRequestContent(
  req: GammaPaymentRequest,
  buyerPubkey: string
): { content: object; tags: string[][] } {
  const tags: string[][] = [
    ['p', buyerPubkey],
    ['subject', 'order-payment'],
    ['type', '2'],
    ['order', req.orderId],
    ['amount', req.amountSats.toString()],
  ];

  if (req.lightning) tags.push(['payment', 'lightning', req.lightning]);
  if (req.bitcoin) tags.push(['payment', 'bitcoin', req.bitcoin]);
  if (req.ecash) tags.push(['payment', 'ecash', req.ecash]);
  if (req.expiration) tags.push(['expiration', req.expiration.toString()]);

  return {
    content: { type: 2, order: req.orderId },
    tags,
  };
}

/** Build kind 16 status update message */
function buildStatusUpdateContent(
  update: GammaStatusUpdate,
  recipientPubkey: string
): { content: object; tags: string[][] } {
  const tags: string[][] = [
    ['p', recipientPubkey],
    ['subject', 'order-info'],
    ['type', '3'],
    ['order', update.orderId],
    ['status', update.status],
  ];

  return {
    content: { type: 3, order: update.orderId, status: update.status },
    tags,
  };
}

/** Build kind 16 shipping update message (merchant → buyer) */
function buildShippingUpdateContent(
  update: GammaShippingUpdate,
  buyerPubkey: string
): { content: object; tags: string[][] } {
  const tags: string[][] = [
    ['p', buyerPubkey],
    ['subject', 'shipping-info'],
    ['type', '4'],
    ['order', update.orderId],
    ['status', update.status],
  ];

  if (update.trackingNumber) tags.push(['tracking', update.trackingNumber]);
  if (update.carrier) tags.push(['carrier', update.carrier]);
  if (update.eta) tags.push(['eta', update.eta.toString()]);

  return {
    content: { type: 4, order: update.orderId, status: update.status },
    tags,
  };
}

// ─── Hooks ─────────────────────────────────────────────────────────────────────

/**
 * Place an order by sending an encrypted kind 16 message to the merchant.
 * This implements the Gamma Spec "Order Creation" (type 1) message.
 */
export function usePlaceGammaOrder() {
  const { nostr } = useNostr();
  const { user } = useCurrentUser();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const adminPubkey = getAdminPubkeyHex();

  return useMutation({
    mutationFn: async (order: GammaOrder) => {
      if (!user) throw new Error('Must be logged in to place an order');

      const { content, tags } = buildOrderCreationContent(order, adminPubkey);

      // Encrypt the content using NIP-44 (preferred) or NIP-04 fallback
      let encryptedContent: string;
      if (user.signer.nip44) {
        encryptedContent = await user.signer.nip44.encrypt(
          adminPubkey,
          JSON.stringify(content)
        );
      } else if (user.signer.nip04) {
        encryptedContent = await user.signer.nip04.encrypt(
          adminPubkey,
          JSON.stringify(content)
        );
      } else {
        throw new Error('Signer does not support encryption (NIP-44 or NIP-04 required)');
      }

      const orderEvent = {
        kind: 16 as const,
        content: encryptedContent,
        tags,
        created_at: Math.floor(Date.now() / 1000),
      };

      const signed = await user.signer.signEvent(orderEvent);
      await nostr.event(signed, { signal: AbortSignal.timeout(10000) });

      // Also store locally so admin sees it immediately
      const localOrder: Order = {
        id: `gamma-${order.orderId}`,
        order_number: `GAMMA-${order.orderId.slice(0, 8).toUpperCase()}`,
        status: 'pending',
        items: order.items.map(item => ({
          product_id: item.productRef,
          product_name: item.productName || item.productRef,
          quantity: item.quantity,
          price: 0,
          currency: 'SAT',
          type: 'physical',
        })),
        total_price: order.amountSats,
        currency: 'SAT',
        buyer_npub: undefined,
        shipping_address: order.address
          ? { line1: order.address, city: '', postal_code: '', country: '' }
          : undefined,
        notes: order.notes,
        source: 'checkout',
        payment_method: 'Lightning',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };
      storeOrder(localOrder);

      return { order, eventId: signed.id };
    },
    onSuccess: (data) => {
      toast({
        title: 'Order Placed!',
        description: `Your order #${data.order.orderId.slice(0, 8)} has been sent to the merchant.`,
      });
      queryClient.invalidateQueries({ queryKey: ['shop-orders'] });
      queryClient.invalidateQueries({ queryKey: ['gamma-orders'] });
    },
    onError: (error) => {
      console.error('Failed to place order:', error);
      toast({
        title: 'Order Failed',
        description: error instanceof Error ? error.message : 'Could not place the order. Please try again.',
        variant: 'destructive',
      });
    },
  });
}

/**
 * Send a payment request to a buyer (merchant only).
 */
export function useSendPaymentRequest() {
  const { nostr } = useNostr();
  const { user } = useCurrentUser();
  const { toast } = useToast();
  const adminPubkey = getAdminPubkeyHex();

  return useMutation({
    mutationFn: async ({
      req,
      buyerPubkey,
    }: {
      req: GammaPaymentRequest;
      buyerPubkey: string;
    }) => {
      if (!user) throw new Error('Must be logged in');
      if (user.pubkey !== adminPubkey) throw new Error('Only the merchant can send payment requests');

      const { content, tags } = buildPaymentRequestContent(req, buyerPubkey);

      let encryptedContent: string;
      if (user.signer.nip44) {
        encryptedContent = await user.signer.nip44.encrypt(buyerPubkey, JSON.stringify(content));
      } else if (user.signer.nip04) {
        encryptedContent = await user.signer.nip04.encrypt(buyerPubkey, JSON.stringify(content));
      } else {
        throw new Error('Signer does not support encryption');
      }

      const event = {
        kind: 16 as const,
        content: encryptedContent,
        tags,
        created_at: Math.floor(Date.now() / 1000),
      };

      const signed = await user.signer.signEvent(event);
      await nostr.event(signed, { signal: AbortSignal.timeout(10000) });
      return signed;
    },
    onSuccess: () => {
      toast({ title: 'Payment Request Sent', description: 'Buyer has been notified.' });
    },
    onError: () => {
      toast({ title: 'Failed', description: 'Could not send payment request.', variant: 'destructive' });
    },
  });
}

/**
 * Update order status (merchant → buyer, or buyer cancel).
 */
export function useSendOrderStatusUpdate() {
  const { nostr } = useNostr();
  const { user } = useCurrentUser();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({
      update,
      recipientPubkey,
    }: {
      update: GammaStatusUpdate;
      recipientPubkey: string;
    }) => {
      if (!user) throw new Error('Must be logged in');

      const { content, tags } = buildStatusUpdateContent(update, recipientPubkey);

      let encryptedContent: string;
      if (user.signer.nip44) {
        encryptedContent = await user.signer.nip44.encrypt(recipientPubkey, JSON.stringify(content));
      } else if (user.signer.nip04) {
        encryptedContent = await user.signer.nip04.encrypt(recipientPubkey, JSON.stringify(content));
      } else {
        throw new Error('Signer does not support encryption');
      }

      const event = {
        kind: 16 as const,
        content: encryptedContent,
        tags,
        created_at: Math.floor(Date.now() / 1000),
      };

      const signed = await user.signer.signEvent(event);
      await nostr.event(signed, { signal: AbortSignal.timeout(10000) });
      return signed;
    },
    onSuccess: (_, vars) => {
      toast({ title: 'Status Updated', description: `Order status: ${vars.update.status}` });
    },
    onError: () => {
      toast({ title: 'Failed', description: 'Could not send status update.', variant: 'destructive' });
    },
  });
}

/**
 * Send a shipping update (merchant → buyer).
 */
export function useSendShippingUpdate() {
  const { nostr } = useNostr();
  const { user } = useCurrentUser();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({
      update,
      buyerPubkey,
    }: {
      update: GammaShippingUpdate;
      buyerPubkey: string;
    }) => {
      if (!user) throw new Error('Must be logged in');

      const { content, tags } = buildShippingUpdateContent(update, buyerPubkey);

      let encryptedContent: string;
      if (user.signer.nip44) {
        encryptedContent = await user.signer.nip44.encrypt(buyerPubkey, JSON.stringify(content));
      } else if (user.signer.nip04) {
        encryptedContent = await user.signer.nip04.encrypt(buyerPubkey, JSON.stringify(content));
      } else {
        throw new Error('Signer does not support encryption');
      }

      const event = {
        kind: 16 as const,
        content: encryptedContent,
        tags,
        created_at: Math.floor(Date.now() / 1000),
      };

      const signed = await user.signer.signEvent(event);
      await nostr.event(signed, { signal: AbortSignal.timeout(10000) });
      return signed;
    },
    onSuccess: () => {
      toast({ title: 'Shipping Update Sent' });
    },
    onError: () => {
      toast({ title: 'Failed', description: 'Could not send shipping update.', variant: 'destructive' });
    },
  });
}

/**
 * Fetch incoming Gamma Spec order messages for the admin (merchant).
 * Decrypts kind 16 messages addressed to the admin pubkey.
 */
export function useGammaOrderMessages() {
  const { nostr } = useNostr();
  const { user } = useCurrentUser();
  const adminPubkey = getAdminPubkeyHex();

  return useQuery({
    queryKey: ['gamma-orders', adminPubkey],
    queryFn: async (c) => {
      if (!user || user.pubkey !== adminPubkey) return [];

      const signal = AbortSignal.any([c.signal, AbortSignal.timeout(10000)]);
      const events = await nostr.query([
        { kinds: [16], '#p': [adminPubkey], limit: 200 },
      ], { signal });

      const decrypted: Array<{
        eventId: string;
        buyerPubkey: string;
        type: number;
        orderId?: string;
        status?: string;
        items?: GammaOrderItem[];
        raw: object;
        createdAt: number;
      }> = [];

      for (const event of events) {
        try {
          let plaintext: string | undefined;
          if (user.signer.nip44) {
            plaintext = await user.signer.nip44.decrypt(event.pubkey, event.content);
          } else if (user.signer.nip04) {
            plaintext = await user.signer.nip04.decrypt(event.pubkey, event.content);
          }
          if (!plaintext) continue;

          const msg = JSON.parse(plaintext) as Record<string, unknown>;
          const msgType = Number(msg.type);
          if (!msgType) continue;

          const orderId = event.tags.find(([t]) => t === 'order')?.[1];
          const status = event.tags.find(([t]) => t === 'status')?.[1];
          const itemTags = event.tags.filter(([t]) => t === 'item');
          const items: GammaOrderItem[] = itemTags.map(([, ref, qty]) => ({
            productRef: ref || '',
            quantity: Number(qty) || 1,
          }));

          decrypted.push({
            eventId: event.id,
            buyerPubkey: event.pubkey,
            type: msgType,
            orderId,
            status,
            items: items.length > 0 ? items : undefined,
            raw: msg,
            createdAt: event.created_at,
          });
        } catch {
          // Couldn't decrypt — skip
        }
      }

      return decrypted.sort((a, b) => b.createdAt - a.createdAt);
    },
    enabled: !!user && user.pubkey === adminPubkey,
    staleTime: 30_000,
    refetchInterval: 60_000,
  });
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

/** Generate a unique order ID */
export function generateOrderId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

/** Convert a product event address to GammaOrderItem */
export function productToOrderItem(
  productId: string,
  pubkey: string,
  quantity: number,
  productName?: string
): GammaOrderItem {
  return {
    productRef: `30402:${pubkey}:${productId}`,
    quantity,
    productName,
  };
}
